### ISSUE TITLE
Rename client

### ISSUE THREAD

**Issue by lliming** [XSEDE/globus-ssh#40]
The client needs to be renamed from globus-ssh to something more generically OAuth, like maybe oauth-ssh.

- Rename this GitHub repo
- Rename the SSH client wrapper script (CLI)

**Comment by JasonAlt** [comment]
This is next in the queue as part of a quick re branding effort. Let's replace 'globus' with 'oauth' as a first pass.

**Comment by JasonAlt** [comment]
The first iteration of this is complete. The changes live in branch issue/40. I'm waiting to hear about the possibility to distribute this via xsede package repos before pushing this to master since that will make a difference on the documentation and how we make this change available.

**Comment by JasonAlt** [comment]
Client will be released through https://software.xsede.org/development/. Instructions updated. Awaiting write access to repo.

**Comment by JasonAlt** [comment]
Deleted:
  https://pypi.org/project/globus-ssh/
  https://github.com/xsede/globus-ssh-server

Created:
  https://pypi.org/project/oauth-ssh/
  https://github.com/xsede/oauth-ssh (renamed from globus-ssh-client)
